#*****************************************************************************************
# Vivado (TM) v2018.2 (64-bit)
#
# test.tcl: Tcl script for re-creating project 'project_1'
#
# Generated by Vivado on Fri Feb 08 16:21:42 CET 2019
# IP Build 2256618 on Thu Jun 14 22:10:49 MDT 2018
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (test.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    "$origin_dir/design_1_wrapper.v"
#    "$origin_dir/design_1_wrapper_behav.wcfg"
#
# 3. The following remote source files that were added to the original project:-
#
#    "$origin_dir/../verilog/RAMB16BWER.v"
#    "$origin_dir/../verilog/add.v"
#    "$origin_dir/../verilog/alu.v"
#    "$origin_dir/../verilog/aluctrl.v"
#    "$origin_dir/../verilog/branch_ctrl.v"
#    "$origin_dir/../verilog/bytewrite_tdp_ram_nc.v"
#    "$origin_dir/../verilog/ctrl.v"
#    "$origin_dir/../verilog/decoder.v"
#    "$origin_dir/../verilog/hazard.v"
#    "$origin_dir/../verilog/hazard_ctrl.v"
#    "$origin_dir/../verilog/imm2word.v"
#    "$origin_dir/../verilog/memdev.v"
#    "$origin_dir/../verilog/mmips_defines.v"
#    "$origin_dir/../verilog/mmips.v"
#    "$origin_dir/../verilog/mux.v"
#    "$origin_dir/../verilog/ram.v"
#    "$origin_dir/../verilog/regfile16.v"
#    "$origin_dir/../verilog/register.v"
#    "$origin_dir/../verilog/rom.v"
#    "$origin_dir/../verilog/shift.v"
#    "$origin_dir/../verilog/signextend.v"
#    "$origin_dir/../verilog/mMIPS_sim.v"
#    "$origin_dir/../verilog/testbench.v"
#    "$origin_dir/../memory/rom/mips_rom32.hex"
#    "$origin_dir/../memory/ram/mips_ram03.hex"
#    "$origin_dir/../memory/ram/mips_ram46.hex"
#    "$origin_dir/../memory/rom/mips_rom40.hex"
#    "$origin_dir/../memory/rom/mips_rom16.hex"
#    "$origin_dir/../memory/rom/mips_rom14.hex"
#    "$origin_dir/../memory/rom/mips_rom22.hex"
#    "$origin_dir/../memory/ram/mips_ram05.hex"
#    "$origin_dir/../memory/ram/mips_ram54.hex"
#    "$origin_dir/../memory/ram/mips_ram11.hex"
#    "$origin_dir/../memory/rom/mips_rom08.hex"
#    "$origin_dir/../memory/ram/mips_ram62.hex"
#    "$origin_dir/../memory/rom/mips_rom30.hex"
#    "$origin_dir/../memory/ram/mips_ram36.hex"
#    "$origin_dir/../memory/ram/mips_ram23.hex"
#    "$origin_dir/../memory/ram/mips_ram28.hex"
#    "$origin_dir/../memory/rom/mips_rom12.hex"
#    "$origin_dir/../memory/rom/mips_rom18.hex"
#    "$origin_dir/../memory/rom/mips_rom42.hex"
#    "$origin_dir/../memory/ram/mips_ram48.hex"
#    "$origin_dir/../memory/ram/mips_ram52.hex"
#    "$origin_dir/../memory/rom/mips_rom24.hex"
#    "$origin_dir/../memory/rom/mips_rom37.hex"
#    "$origin_dir/../memory/ram/mips_ram21.hex"
#    "$origin_dir/../memory/rom/mips_rom06.hex"
#    "$origin_dir/../memory/ram/mips_ram34.hex"
#    "$origin_dir/../memory/rom/mips_rom10.hex"
#    "$origin_dir/../memory/rom/mips_rom45.hex"
#    "$origin_dir/../memory/rom/mips_rom36.hex"
#    "$origin_dir/../memory/ram/mips_ram09.hex"
#    "$origin_dir/../memory/ram/mips_ram18.hex"
#    "$origin_dir/../memory/ram/mips_ram41.hex"
#    "$origin_dir/../memory/ram/mips_ram24.hex"
#    "$origin_dir/../memory/ram/mips_ram15.hex"
#    "$origin_dir/../memory/rom/mips_rom43.hex"
#    "$origin_dir/../memory/ram/mips_ram32.hex"
#    "$origin_dir/../memory/rom/mips_rom00.hex"
#    "$origin_dir/../memory/ram/mips_ram58.hex"
#    "$origin_dir/../memory/rom/mips_rom26.hex"
#    "$origin_dir/../memory/rom/mips_rom39.hex"
#    "$origin_dir/../memory/rom/mips_rom04.hex"
#    "$origin_dir/../memory/rom/mips_rom09.hex"
#    "$origin_dir/../memory/rom/mips_rom34.hex"
#    "$origin_dir/../memory/rom/mips_rom21.hex"
#    "$origin_dir/../memory/rom/mips_rom47.hex"
#    "$origin_dir/../memory/ram/mips_ram07.hex"
#    "$origin_dir/../memory/ram/mips_ram43.hex"
#    "$origin_dir/../memory/ram/mips_ram60.hex"
#    "$origin_dir/../memory/ram/mips_ram00.hex"
#    "$origin_dir/../memory/ram/mips_ram30.hex"
#    "$origin_dir/../memory/ram/mips_ram26.hex"
#    "$origin_dir/../memory/ram/mips_ram13.hex"
#    "$origin_dir/../memory/ram/mips_ram56.hex"
#    "$origin_dir/../memory/rom/mips_rom15.hex"
#    "$origin_dir/../memory/rom/mips_rom28.hex"
#    "$origin_dir/../memory/rom/mips_rom02.hex"
#    "$origin_dir/../memory/ram/mips_ram55.hex"
#    "$origin_dir/../memory/ram/mips_ram12.hex"
#    "$origin_dir/../memory/ram/mips_ram39.hex"
#    "$origin_dir/../memory/rom/mips_rom07.hex"
#    "$origin_dir/../memory/rom/mips_rom23.hex"
#    "$origin_dir/../memory/ram/mips_ram63.hex"
#    "$origin_dir/../memory/rom/mips_rom31.hex"
#    "$origin_dir/../memory/ram/mips_ram20.hex"
#    "$origin_dir/../memory/ram/mips_ram37.hex"
#    "$origin_dir/../memory/ram/mips_ram02.hex"
#    "$origin_dir/../memory/rom/mips_rom13.hex"
#    "$origin_dir/../memory/ram/mips_ram45.hex"
#    "$origin_dir/../memory/ram/mips_ram06.hex"
#    "$origin_dir/../memory/rom/mips_rom17.hex"
#    "$origin_dir/../memory/ram/mips_ram49.hex"
#    "$origin_dir/../memory/ram/mips_ram10.hex"
#    "$origin_dir/../memory/ram/mips_ram53.hex"
#    "$origin_dir/../memory/ram/mips_ram22.hex"
#    "$origin_dir/../memory/rom/mips_rom05.hex"
#    "$origin_dir/../memory/rom/mips_rom25.hex"
#    "$origin_dir/../memory/ram/mips_ram40.hex"
#    "$origin_dir/../memory/ram/mips_ram16.hex"
#    "$origin_dir/../memory/ram/mips_ram35.hex"
#    "$origin_dir/../memory/ram/mips_ram29.hex"
#    "$origin_dir/../memory/ram/mips_ram51.hex"
#    "$origin_dir/../memory/rom/mips_rom19.hex"
#    "$origin_dir/../memory/ram/mips_ram47.hex"
#    "$origin_dir/../memory/rom/mips_rom41.hex"
#    "$origin_dir/../memory/ram/mips_ram04.hex"
#    "$origin_dir/../memory/rom/mips_rom11.hex"
#    "$origin_dir/../memory/ram/mips_ram17.hex"
#    "$origin_dir/../memory/ram/mips_ram42.hex"
#    "$origin_dir/../memory/ram/mips_ram25.hex"
#    "$origin_dir/../memory/ram/mips_ram50.hex"
#    "$origin_dir/../memory/rom/mips_rom44.hex"
#    "$origin_dir/../memory/ram/mips_ram33.hex"
#    "$origin_dir/../memory/rom/mips_rom01.hex"
#    "$origin_dir/../memory/rom/mips_rom29.hex"
#    "$origin_dir/../memory/ram/mips_ram59.hex"
#    "$origin_dir/../memory/ram/mips_ram27.hex"
#    "$origin_dir/../memory/rom/mips_rom35.hex"
#    "$origin_dir/../memory/rom/mips_rom38.hex"
#    "$origin_dir/../memory/ram/mips_ram19.hex"
#    "$origin_dir/../memory/ram/mips_ram61.hex"
#    "$origin_dir/../memory/ram/mips_ram.dump.hex"
#    "$origin_dir/../memory/ram/mips_ram01.hex"
#    "$origin_dir/../memory/ram/mips_ram14.hex"
#    "$origin_dir/../memory/ram/mips_ram57.hex"
#    "$origin_dir/../memory/ram/mips_ram31.hex"
#    "$origin_dir/../memory/ram/mips_ram44.hex"
#    "$origin_dir/../memory/rom/mips_rom03.hex"
#    "$origin_dir/../memory/rom/mips_rom27.hex"
#    "$origin_dir/../memory/rom/mips_rom46.hex"
#    "$origin_dir/../memory/rom/mips_rom20.hex"
#    "$origin_dir/../memory/rom/mips_rom33.hex"
#    "$origin_dir/../memory/ram/mips_ram38.hex"
#    "$origin_dir/../memory/ram/mips_ram08.hex"
#
#*****************************************************************************************

# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

# Set the project name
set _xil_proj_name_ "project_1"

# Use project name variable, if specified in the tcl shell
if { [info exists ::user_project_name] } {
  set _xil_proj_name_ $::user_project_name
}

variable script_file
set script_file "create_project.tcl"

# Help information for this script
proc help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--project_name <name>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--project_name <name>\] Create project with the specified name. Default"
  puts "                       name is the name of the project from where this"
  puts "                       script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < $::argc} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir"   { incr i; set origin_dir [lindex $::argv $i] }
      "--project_name" { incr i; set _xil_proj_name_ [lindex $::argv $i] }
      "--help"         { help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/"]"

# Create project
create_project ${_xil_proj_name_} ./${_xil_proj_name_} -part xc7z020clg400-1

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Reconstruct message rules
# None

# Set project properties
set obj [current_project]
set_property -name "board_part" -value "tul.com.tw:pynq-z2:part0:1.0" -objects $obj
set_property -name "default_lib" -value "xil_defaultlib" -objects $obj
set_property -name "dsa.accelerator_binary_content" -value "bitstream" -objects $obj
set_property -name "dsa.accelerator_binary_format" -value "xclbin2" -objects $obj
set_property -name "dsa.board_id" -value "pynq-z2" -objects $obj
set_property -name "dsa.description" -value "Vivado generated DSA" -objects $obj
set_property -name "dsa.dr_bd_base_address" -value "0" -objects $obj
set_property -name "dsa.emu_dir" -value "emu" -objects $obj
set_property -name "dsa.flash_interface_type" -value "bpix16" -objects $obj
set_property -name "dsa.flash_offset_address" -value "0" -objects $obj
set_property -name "dsa.flash_size" -value "1024" -objects $obj
set_property -name "dsa.host_architecture" -value "x86_64" -objects $obj
set_property -name "dsa.host_interface" -value "pcie" -objects $obj
set_property -name "dsa.num_compute_units" -value "60" -objects $obj
set_property -name "dsa.platform_state" -value "pre_synth" -objects $obj
set_property -name "dsa.uses_pr" -value "1" -objects $obj
set_property -name "dsa.vendor" -value "xilinx" -objects $obj
set_property -name "dsa.version" -value "0.0" -objects $obj
set_property -name "enable_vhdl_2008" -value "1" -objects $obj
set_property -name "ip_cache_permissions" -value "read write" -objects $obj
set_property -name "ip_output_repo" -value "$proj_dir/${_xil_proj_name_}.cache/ip" -objects $obj
set_property -name "mem.enable_memory_map_generation" -value "1" -objects $obj
set_property -name "sim.central_dir" -value "$proj_dir/${_xil_proj_name_}.ip_user_files" -objects $obj
set_property -name "sim.ip.auto_export_scripts" -value "1" -objects $obj
set_property -name "simulator_language" -value "Mixed" -objects $obj
set_property -name "webtalk.activehdl_export_sim" -value "4" -objects $obj
set_property -name "webtalk.ies_export_sim" -value "4" -objects $obj
set_property -name "webtalk.modelsim_export_sim" -value "4" -objects $obj
set_property -name "webtalk.questa_export_sim" -value "4" -objects $obj
set_property -name "webtalk.riviera_export_sim" -value "4" -objects $obj
set_property -name "webtalk.vcs_export_sim" -value "4" -objects $obj
set_property -name "webtalk.xsim_export_sim" -value "4" -objects $obj
set_property -name "webtalk.xsim_launch_sim" -value "15" -objects $obj
set_property -name "xpm_libraries" -value "XPM_FIFO XPM_MEMORY" -objects $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
set files [list \
 [file normalize "${origin_dir}/../verilog/RAMB16BWER.v"] \
 [file normalize "${origin_dir}/../verilog/add.v"] \
 [file normalize "${origin_dir}/../verilog/alu.v"] \
 [file normalize "${origin_dir}/../verilog/aluctrl.v"] \
 [file normalize "${origin_dir}/../verilog/branch_ctrl.v"] \
 [file normalize "${origin_dir}/../verilog/bytewrite_tdp_ram_nc.v"] \
 [file normalize "${origin_dir}/../verilog/ctrl.v"] \
 [file normalize "${origin_dir}/../verilog/decoder.v"] \
 [file normalize "${origin_dir}/../verilog/hazard.v"] \
 [file normalize "${origin_dir}/../verilog/hazard_ctrl.v"] \
 [file normalize "${origin_dir}/../verilog/imm2word.v"] \
 [file normalize "${origin_dir}/../verilog/memdev.v"] \
 [file normalize "${origin_dir}/../verilog/mmips_defines.v"] \
 [file normalize "${origin_dir}/../verilog/mmips.v"] \
 [file normalize "${origin_dir}/../verilog/mux.v"] \
 [file normalize "${origin_dir}/../verilog/ram.v"] \
 [file normalize "${origin_dir}/../verilog/regfile16.v"] \
 [file normalize "${origin_dir}/../verilog/register.v"] \
 [file normalize "${origin_dir}/../verilog/rom.v"] \
 [file normalize "${origin_dir}/../verilog/shift.v"] \
 [file normalize "${origin_dir}/../verilog/signextend.v"] \
 [file normalize "${origin_dir}/../verilog/mMIPS_sim.v"] \
]
add_files -norecurse -fileset $obj $files

# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/design_1_wrapper.v" ]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property -name "top" -value "design_1_wrapper" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]


# Empty (no sources present)

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
set files [list \
 [file normalize "${origin_dir}/../memory/rom/mips_rom32.hex"] \
 [file normalize "${origin_dir}/../memory/ram/mips_ram03.hex"] \
 [file normalize "${origin_dir}/../memory/ram/mips_ram46.hex"] \
 [file normalize "${origin_dir}/../memory/rom/mips_rom40.hex"] \
 [file normalize "${origin_dir}/../memory/rom/mips_rom16.hex"] \
 [file normalize "${origin_dir}/../memory/rom/mips_rom14.hex"] \
 [file normalize "${origin_dir}/../memory/rom/mips_rom22.hex"] \
 [file normalize "${origin_dir}/../memory/ram/mips_ram05.hex"] \
 [file normalize "${origin_dir}/../memory/ram/mips_ram54.hex"] \
 [file normalize "${origin_dir}/../memory/ram/mips_ram11.hex"] \
 [file normalize "${origin_dir}/../memory/rom/mips_rom08.hex"] \
 [file normalize "${origin_dir}/../memory/ram/mips_ram62.hex"] \
 [file normalize "${origin_dir}/../memory/rom/mips_rom30.hex"] \
 [file normalize "${origin_dir}/../memory/ram/mips_ram36.hex"] \
 [file normalize "${origin_dir}/../memory/ram/mips_ram23.hex"] \
 [file normalize "${origin_dir}/../memory/ram/mips_ram28.hex"] \
 [file normalize "${origin_dir}/../memory/rom/mips_rom12.hex"] \
 [file normalize "${origin_dir}/../memory/rom/mips_rom18.hex"] \
 [file normalize "${origin_dir}/../memory/rom/mips_rom42.hex"] \
 [file normalize "${origin_dir}/../memory/ram/mips_ram48.hex"] \
 [file normalize "${origin_dir}/../memory/ram/mips_ram52.hex"] \
 [file normalize "${origin_dir}/../memory/rom/mips_rom24.hex"] \
 [file normalize "${origin_dir}/../memory/rom/mips_rom37.hex"] \
 [file normalize "${origin_dir}/../memory/ram/mips_ram21.hex"] \
 [file normalize "${origin_dir}/../memory/rom/mips_rom06.hex"] \
 [file normalize "${origin_dir}/../memory/ram/mips_ram34.hex"] \
 [file normalize "${origin_dir}/../memory/rom/mips_rom10.hex"] \
 [file normalize "${origin_dir}/../memory/rom/mips_rom45.hex"] \
 [file normalize "${origin_dir}/../memory/rom/mips_rom36.hex"] \
 [file normalize "${origin_dir}/../memory/ram/mips_ram09.hex"] \
 [file normalize "${origin_dir}/../memory/ram/mips_ram18.hex"] \
 [file normalize "${origin_dir}/../memory/ram/mips_ram41.hex"] \
 [file normalize "${origin_dir}/../memory/ram/mips_ram24.hex"] \
 [file normalize "${origin_dir}/../memory/ram/mips_ram15.hex"] \
 [file normalize "${origin_dir}/../memory/rom/mips_rom43.hex"] \
 [file normalize "${origin_dir}/../memory/ram/mips_ram32.hex"] \
 [file normalize "${origin_dir}/../memory/rom/mips_rom00.hex"] \
 [file normalize "${origin_dir}/../memory/ram/mips_ram58.hex"] \
 [file normalize "${origin_dir}/../memory/rom/mips_rom26.hex"] \
 [file normalize "${origin_dir}/../memory/rom/mips_rom39.hex"] \
 [file normalize "${origin_dir}/../memory/rom/mips_rom04.hex"] \
 [file normalize "${origin_dir}/../memory/rom/mips_rom09.hex"] \
 [file normalize "${origin_dir}/../memory/rom/mips_rom34.hex"] \
 [file normalize "${origin_dir}/../memory/rom/mips_rom21.hex"] \
 [file normalize "${origin_dir}/../memory/rom/mips_rom47.hex"] \
 [file normalize "${origin_dir}/../memory/ram/mips_ram07.hex"] \
 [file normalize "${origin_dir}/../memory/ram/mips_ram43.hex"] \
 [file normalize "${origin_dir}/../memory/ram/mips_ram60.hex"] \
 [file normalize "${origin_dir}/../memory/ram/mips_ram00.hex"] \
 [file normalize "${origin_dir}/../memory/ram/mips_ram30.hex"] \
 [file normalize "${origin_dir}/../memory/ram/mips_ram26.hex"] \
 [file normalize "${origin_dir}/../memory/ram/mips_ram13.hex"] \
 [file normalize "${origin_dir}/../memory/ram/mips_ram56.hex"] \
 [file normalize "${origin_dir}/../memory/rom/mips_rom15.hex"] \
 [file normalize "${origin_dir}/../memory/rom/mips_rom28.hex"] \
 [file normalize "${origin_dir}/../memory/rom/mips_rom02.hex"] \
 [file normalize "${origin_dir}/../memory/ram/mips_ram55.hex"] \
 [file normalize "${origin_dir}/../memory/ram/mips_ram12.hex"] \
 [file normalize "${origin_dir}/../memory/ram/mips_ram39.hex"] \
 [file normalize "${origin_dir}/../memory/rom/mips_rom07.hex"] \
 [file normalize "${origin_dir}/../memory/rom/mips_rom23.hex"] \
 [file normalize "${origin_dir}/../memory/ram/mips_ram63.hex"] \
 [file normalize "${origin_dir}/../memory/rom/mips_rom31.hex"] \
 [file normalize "${origin_dir}/../memory/ram/mips_ram20.hex"] \
 [file normalize "${origin_dir}/../memory/ram/mips_ram37.hex"] \
 [file normalize "${origin_dir}/../memory/ram/mips_ram02.hex"] \
 [file normalize "${origin_dir}/../memory/rom/mips_rom13.hex"] \
 [file normalize "${origin_dir}/../memory/ram/mips_ram45.hex"] \
 [file normalize "${origin_dir}/../memory/ram/mips_ram06.hex"] \
 [file normalize "${origin_dir}/../memory/rom/mips_rom17.hex"] \
 [file normalize "${origin_dir}/../memory/ram/mips_ram49.hex"] \
 [file normalize "${origin_dir}/../memory/ram/mips_ram10.hex"] \
 [file normalize "${origin_dir}/../memory/ram/mips_ram53.hex"] \
 [file normalize "${origin_dir}/../memory/ram/mips_ram22.hex"] \
 [file normalize "${origin_dir}/../memory/rom/mips_rom05.hex"] \
 [file normalize "${origin_dir}/../memory/rom/mips_rom25.hex"] \
 [file normalize "${origin_dir}/../memory/ram/mips_ram40.hex"] \
 [file normalize "${origin_dir}/../memory/ram/mips_ram16.hex"] \
 [file normalize "${origin_dir}/../memory/ram/mips_ram35.hex"] \
 [file normalize "${origin_dir}/../memory/ram/mips_ram29.hex"] \
 [file normalize "${origin_dir}/../memory/ram/mips_ram51.hex"] \
 [file normalize "${origin_dir}/../memory/rom/mips_rom19.hex"] \
 [file normalize "${origin_dir}/../memory/ram/mips_ram47.hex"] \
 [file normalize "${origin_dir}/../memory/rom/mips_rom41.hex"] \
 [file normalize "${origin_dir}/../memory/ram/mips_ram04.hex"] \
 [file normalize "${origin_dir}/../memory/rom/mips_rom11.hex"] \
 [file normalize "${origin_dir}/../memory/ram/mips_ram17.hex"] \
 [file normalize "${origin_dir}/../memory/ram/mips_ram42.hex"] \
 [file normalize "${origin_dir}/../memory/ram/mips_ram25.hex"] \
 [file normalize "${origin_dir}/../memory/ram/mips_ram50.hex"] \
 [file normalize "${origin_dir}/../memory/rom/mips_rom44.hex"] \
 [file normalize "${origin_dir}/../memory/ram/mips_ram33.hex"] \
 [file normalize "${origin_dir}/../memory/rom/mips_rom01.hex"] \
 [file normalize "${origin_dir}/../memory/rom/mips_rom29.hex"] \
 [file normalize "${origin_dir}/../memory/ram/mips_ram59.hex"] \
 [file normalize "${origin_dir}/../memory/ram/mips_ram27.hex"] \
 [file normalize "${origin_dir}/../memory/rom/mips_rom35.hex"] \
 [file normalize "${origin_dir}/../memory/rom/mips_rom38.hex"] \
 [file normalize "${origin_dir}/../memory/ram/mips_ram19.hex"] \
 [file normalize "${origin_dir}/../memory/ram/mips_ram61.hex"] \
 [file normalize "${origin_dir}/../memory/ram/mips_ram.dump.hex"] \
 [file normalize "${origin_dir}/../memory/ram/mips_ram01.hex"] \
 [file normalize "${origin_dir}/../memory/ram/mips_ram14.hex"] \
 [file normalize "${origin_dir}/../memory/ram/mips_ram57.hex"] \
 [file normalize "${origin_dir}/../memory/ram/mips_ram31.hex"] \
 [file normalize "${origin_dir}/../memory/ram/mips_ram44.hex"] \
 [file normalize "${origin_dir}/../memory/rom/mips_rom03.hex"] \
 [file normalize "${origin_dir}/../memory/rom/mips_rom27.hex"] \
 [file normalize "${origin_dir}/../memory/rom/mips_rom46.hex"] \
 [file normalize "${origin_dir}/../memory/rom/mips_rom20.hex"] \
 [file normalize "${origin_dir}/../memory/rom/mips_rom33.hex"] \
 [file normalize "${origin_dir}/../memory/ram/mips_ram38.hex"] \
 [file normalize "${origin_dir}/../memory/ram/mips_ram08.hex"] \
 [file normalize "${origin_dir}/../verilog/testbench.v"] \
]
add_files -norecurse -fileset $obj $files

# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/design_1_wrapper_behav.wcfg" ]\
]
set imported_files [import_files -fileset sim_1 $files]

# Set 'sim_1' fileset file properties for remote files
set file "$origin_dir/../memory/rom/mips_rom32.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/ram/mips_ram03.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/ram/mips_ram46.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/rom/mips_rom40.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/rom/mips_rom16.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/rom/mips_rom14.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/rom/mips_rom22.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/ram/mips_ram05.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/ram/mips_ram54.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/ram/mips_ram11.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/rom/mips_rom08.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/ram/mips_ram62.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/rom/mips_rom30.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/ram/mips_ram36.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/ram/mips_ram23.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/ram/mips_ram28.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/rom/mips_rom12.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/rom/mips_rom18.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/rom/mips_rom42.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/ram/mips_ram48.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/ram/mips_ram52.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/rom/mips_rom24.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/rom/mips_rom37.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/ram/mips_ram21.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/rom/mips_rom06.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/ram/mips_ram34.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/rom/mips_rom10.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/rom/mips_rom45.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/rom/mips_rom36.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/ram/mips_ram09.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/ram/mips_ram18.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/ram/mips_ram41.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/ram/mips_ram24.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/ram/mips_ram15.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/rom/mips_rom43.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/ram/mips_ram32.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/rom/mips_rom00.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/ram/mips_ram58.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/rom/mips_rom26.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/rom/mips_rom39.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/rom/mips_rom04.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/rom/mips_rom09.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/rom/mips_rom34.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/rom/mips_rom21.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/rom/mips_rom47.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/ram/mips_ram07.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/ram/mips_ram43.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/ram/mips_ram60.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/ram/mips_ram00.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/ram/mips_ram30.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/ram/mips_ram26.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/ram/mips_ram13.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/ram/mips_ram56.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/rom/mips_rom15.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/rom/mips_rom28.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/rom/mips_rom02.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/ram/mips_ram55.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/ram/mips_ram12.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/ram/mips_ram39.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/rom/mips_rom07.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/rom/mips_rom23.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/ram/mips_ram63.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/rom/mips_rom31.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/ram/mips_ram20.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/ram/mips_ram37.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/ram/mips_ram02.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/rom/mips_rom13.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/ram/mips_ram45.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/ram/mips_ram06.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/rom/mips_rom17.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/ram/mips_ram49.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/ram/mips_ram10.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/ram/mips_ram53.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/ram/mips_ram22.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/rom/mips_rom05.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/rom/mips_rom25.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/ram/mips_ram40.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/ram/mips_ram16.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/ram/mips_ram35.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/ram/mips_ram29.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/ram/mips_ram51.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/rom/mips_rom19.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/ram/mips_ram47.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/rom/mips_rom41.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/ram/mips_ram04.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/rom/mips_rom11.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/ram/mips_ram17.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/ram/mips_ram42.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/ram/mips_ram25.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/ram/mips_ram50.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/rom/mips_rom44.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/ram/mips_ram33.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/rom/mips_rom01.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/rom/mips_rom29.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/ram/mips_ram59.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/ram/mips_ram27.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/rom/mips_rom35.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/rom/mips_rom38.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/ram/mips_ram19.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/ram/mips_ram61.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/ram/mips_ram.dump.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/ram/mips_ram01.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/ram/mips_ram14.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/ram/mips_ram57.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/ram/mips_ram31.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/ram/mips_ram44.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/rom/mips_rom03.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/rom/mips_rom27.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/rom/mips_rom46.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/rom/mips_rom20.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/rom/mips_rom33.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/ram/mips_ram38.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj

set file "$origin_dir/../memory/ram/mips_ram08.hex"
set file [file normalize $file]
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "Unknown" -objects $file_obj


# Set 'sim_1' fileset file properties for local files
# None

# # Set 'sim_1' fileset file properties for remote files
# set file "$origin_dir/../verilog/testbench.v"
# set file [file normalize $file]
# set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
# set_property -name "used_in" -value "simulation" -objects $file_obj
# set_property -name "used_in_implementation" -value "0" -objects $file_obj
# set_property -name "used_in_synthesis" -value "0" -objects $file_obj

# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property -name "top" -value "testbench" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj
set_property -name "top_lib" -value "xil_defaultlib" -objects $obj


# Adding sources referenced in BDs, if not already added
if { [get_files RAMB16BWER.v] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../verilog/RAMB16BWER.v
}
if { [get_files add.v] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../verilog/add.v
}
if { [get_files alu.v] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../verilog/alu.v
}
if { [get_files aluctrl.v] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../verilog/aluctrl.v
}
if { [get_files branch_ctrl.v] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../verilog/branch_ctrl.v
}
if { [get_files bytewrite_tdp_ram_nc.v] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../verilog/bytewrite_tdp_ram_nc.v
}
if { [get_files ctrl.v] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../verilog/ctrl.v
}
if { [get_files decoder.v] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../verilog/decoder.v
}
if { [get_files hazard.v] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../verilog/hazard.v
}
if { [get_files hazard_ctrl.v] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../verilog/hazard_ctrl.v
}
if { [get_files imm2word.v] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../verilog/imm2word.v
}
if { [get_files memdev.v] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../verilog/memdev.v
}
if { [get_files mmips_defines.v] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../verilog/mmips_defines.v
}
if { [get_files mmips.v] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../verilog/mmips.v
}
if { [get_files mux.v] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../verilog/mux.v
}
if { [get_files ram.v] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../verilog/ram.v
}
if { [get_files regfile16.v] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../verilog/regfile16.v
}
if { [get_files register.v] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../verilog/register.v
}
if { [get_files rom.v] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../verilog/rom.v
}
if { [get_files shift.v] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../verilog/shift.v
}
if { [get_files signextend.v] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../verilog/signextend.v
}
if { [get_files mMIPS_sim.v] == "" } {
  import_files -quiet -fileset sources_1 $origin_dir/../verilog/mMIPS_sim.v
}


# Proc to create BD design_1
proc cr_bd_design_1 { parentCell } {
# The design that will be created by this Tcl proc contains the following 
# module references:
# mMIPS_sim



  # CHANGE DESIGN NAME HERE
  set design_name design_1

  common::send_msg_id "BD_TCL-003" "INFO" "Currently there is no design <$design_name> in project, so creating one..."

  create_bd_design $design_name

  set bCheckIPsPassed 1
  ##################################################################
  # CHECK IPs
  ##################################################################
  set bCheckIPs 1
  if { $bCheckIPs == 1 } {
     set list_check_ips "\ 
  xilinx.com:ip:processing_system7:5.5\
  xilinx.com:ip:proc_sys_reset:5.0\
  "

   set list_ips_missing ""
   common::send_msg_id "BD_TCL-006" "INFO" "Checking if the following IPs exist in the project's IP catalog: $list_check_ips ."

   foreach ip_vlnv $list_check_ips {
      set ip_obj [get_ipdefs -all $ip_vlnv]
      if { $ip_obj eq "" } {
         lappend list_ips_missing $ip_vlnv
      }
   }

   if { $list_ips_missing ne "" } {
      catch {common::send_msg_id "BD_TCL-115" "ERROR" "The following IPs are not found in the IP Catalog:\n  $list_ips_missing\n\nResolution: Please add the repository containing the IP(s) to the project." }
      set bCheckIPsPassed 0
   }

  }

  ##################################################################
  # CHECK Modules
  ##################################################################
  set bCheckModules 1
  if { $bCheckModules == 1 } {
     set list_check_mods "\ 
  mMIPS_sim\
  "

   set list_mods_missing ""
   common::send_msg_id "BD_TCL-006" "INFO" "Checking if the following modules exist in the project's sources: $list_check_mods ."

   foreach mod_vlnv $list_check_mods {
      if { [can_resolve_reference $mod_vlnv] == 0 } {
         lappend list_mods_missing $mod_vlnv
      }
   }

   if { $list_mods_missing ne "" } {
      catch {common::send_msg_id "BD_TCL-115" "ERROR" "The following module(s) are not found in the project: $list_mods_missing" }
      common::send_msg_id "BD_TCL-008" "INFO" "Please add source files for the missing module(s) above."
      set bCheckIPsPassed 0
   }
}

  if { $bCheckIPsPassed != 1 } {
    common::send_msg_id "BD_TCL-1003" "WARNING" "Will not continue with creation of design due to the error(s) above."
    return 3
  }

  variable script_folder

  if { $parentCell eq "" } {
     set parentCell [get_bd_cells /]
  }

  # Get object for parentCell
  set parentObj [get_bd_cells $parentCell]
  if { $parentObj == "" } {
     catch {common::send_msg_id "BD_TCL-100" "ERROR" "Unable to find parent cell <$parentCell>!"}
     return
  }

  # Make sure parentObj is hier blk
  set parentType [get_property TYPE $parentObj]
  if { $parentType ne "hier" } {
     catch {common::send_msg_id "BD_TCL-101" "ERROR" "Parent <$parentObj> has TYPE = <$parentType>. Expected to be <hier>."}
     return
  }

  # Save current instance; Restore later
  set oldCurInst [current_bd_instance .]

  # Set parent object as current
  current_bd_instance $parentObj


  # Create interface ports
  set DDR [ create_bd_intf_port -mode Master -vlnv xilinx.com:interface:ddrx_rtl:1.0 DDR ]
  set FIXED_IO [ create_bd_intf_port -mode Master -vlnv xilinx.com:display_processing_system7:fixedio_rtl:1.0 FIXED_IO ]

  # Create ports

  # Create instance: mMIPS_sim_0, and set properties
  set block_name mMIPS_sim
  set block_cell_name mMIPS_sim_0
  if { [catch {set mMIPS_sim_0 [create_bd_cell -type module -reference $block_name $block_cell_name] } errmsg] } {
     catch {common::send_msg_id "BD_TCL-105" "ERROR" "Unable to add referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   } elseif { $mMIPS_sim_0 eq "" } {
     catch {common::send_msg_id "BD_TCL-106" "ERROR" "Unable to referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   }
  
  # Create instance: processing_system7_0, and set properties
  set processing_system7_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:processing_system7:5.5 processing_system7_0 ]
  set_property -dict [ list \
   CONFIG.PCW_ACT_APU_PERIPHERAL_FREQMHZ {666.666687} \
   CONFIG.PCW_ACT_CAN0_PERIPHERAL_FREQMHZ {23.8095} \
   CONFIG.PCW_ACT_CAN1_PERIPHERAL_FREQMHZ {23.8095} \
   CONFIG.PCW_ACT_CAN_PERIPHERAL_FREQMHZ {10.000000} \
   CONFIG.PCW_ACT_DCI_PERIPHERAL_FREQMHZ {10.158730} \
   CONFIG.PCW_ACT_ENET0_PERIPHERAL_FREQMHZ {10.000000} \
   CONFIG.PCW_ACT_ENET1_PERIPHERAL_FREQMHZ {10.000000} \
   CONFIG.PCW_ACT_FPGA0_PERIPHERAL_FREQMHZ {50.000000} \
   CONFIG.PCW_ACT_FPGA1_PERIPHERAL_FREQMHZ {10.000000} \
   CONFIG.PCW_ACT_FPGA2_PERIPHERAL_FREQMHZ {10.000000} \
   CONFIG.PCW_ACT_FPGA3_PERIPHERAL_FREQMHZ {10.000000} \
   CONFIG.PCW_ACT_I2C_PERIPHERAL_FREQMHZ {50} \
   CONFIG.PCW_ACT_PCAP_PERIPHERAL_FREQMHZ {200.000000} \
   CONFIG.PCW_ACT_QSPI_PERIPHERAL_FREQMHZ {10.000000} \
   CONFIG.PCW_ACT_SDIO_PERIPHERAL_FREQMHZ {10.000000} \
   CONFIG.PCW_ACT_SMC_PERIPHERAL_FREQMHZ {10.000000} \
   CONFIG.PCW_ACT_SPI_PERIPHERAL_FREQMHZ {10.000000} \
   CONFIG.PCW_ACT_TPIU_PERIPHERAL_FREQMHZ {200.000000} \
   CONFIG.PCW_ACT_TTC0_CLK0_PERIPHERAL_FREQMHZ {111.111115} \
   CONFIG.PCW_ACT_TTC0_CLK1_PERIPHERAL_FREQMHZ {111.111115} \
   CONFIG.PCW_ACT_TTC0_CLK2_PERIPHERAL_FREQMHZ {111.111115} \
   CONFIG.PCW_ACT_TTC1_CLK0_PERIPHERAL_FREQMHZ {111.111115} \
   CONFIG.PCW_ACT_TTC1_CLK1_PERIPHERAL_FREQMHZ {111.111115} \
   CONFIG.PCW_ACT_TTC1_CLK2_PERIPHERAL_FREQMHZ {111.111115} \
   CONFIG.PCW_ACT_TTC_PERIPHERAL_FREQMHZ {50} \
   CONFIG.PCW_ACT_UART_PERIPHERAL_FREQMHZ {10.000000} \
   CONFIG.PCW_ACT_USB0_PERIPHERAL_FREQMHZ {60} \
   CONFIG.PCW_ACT_USB1_PERIPHERAL_FREQMHZ {60} \
   CONFIG.PCW_ACT_WDT_PERIPHERAL_FREQMHZ {111.111115} \
   CONFIG.PCW_APU_CLK_RATIO_ENABLE {6:2:1} \
   CONFIG.PCW_APU_PERIPHERAL_FREQMHZ {666.666666} \
   CONFIG.PCW_ARMPLL_CTRL_FBDIV {40} \
   CONFIG.PCW_CAN0_BASEADDR {0xE0008000} \
   CONFIG.PCW_CAN0_GRP_CLK_ENABLE {0} \
   CONFIG.PCW_CAN0_HIGHADDR {0xE0008FFF} \
   CONFIG.PCW_CAN0_PERIPHERAL_CLKSRC {External} \
   CONFIG.PCW_CAN0_PERIPHERAL_ENABLE {0} \
   CONFIG.PCW_CAN0_PERIPHERAL_FREQMHZ {-1} \
   CONFIG.PCW_CAN1_BASEADDR {0xE0009000} \
   CONFIG.PCW_CAN1_GRP_CLK_ENABLE {0} \
   CONFIG.PCW_CAN1_HIGHADDR {0xE0009FFF} \
   CONFIG.PCW_CAN1_PERIPHERAL_CLKSRC {External} \
   CONFIG.PCW_CAN1_PERIPHERAL_ENABLE {0} \
   CONFIG.PCW_CAN1_PERIPHERAL_FREQMHZ {-1} \
   CONFIG.PCW_CAN_PERIPHERAL_CLKSRC {IO PLL} \
   CONFIG.PCW_CAN_PERIPHERAL_DIVISOR0 {1} \
   CONFIG.PCW_CAN_PERIPHERAL_DIVISOR1 {1} \
   CONFIG.PCW_CAN_PERIPHERAL_FREQMHZ {100} \
   CONFIG.PCW_CAN_PERIPHERAL_VALID {0} \
   CONFIG.PCW_CLK0_FREQ {50000000} \
   CONFIG.PCW_CLK1_FREQ {10000000} \
   CONFIG.PCW_CLK2_FREQ {10000000} \
   CONFIG.PCW_CLK3_FREQ {10000000} \
   CONFIG.PCW_CORE0_FIQ_INTR {0} \
   CONFIG.PCW_CORE0_IRQ_INTR {0} \
   CONFIG.PCW_CORE1_FIQ_INTR {0} \
   CONFIG.PCW_CORE1_IRQ_INTR {0} \
   CONFIG.PCW_CPU_CPU_6X4X_MAX_RANGE {667} \
   CONFIG.PCW_CPU_CPU_PLL_FREQMHZ {1333.333} \
   CONFIG.PCW_CPU_PERIPHERAL_CLKSRC {ARM PLL} \
   CONFIG.PCW_CPU_PERIPHERAL_DIVISOR0 {2} \
   CONFIG.PCW_CRYSTAL_PERIPHERAL_FREQMHZ {33.333333} \
   CONFIG.PCW_DCI_PERIPHERAL_CLKSRC {DDR PLL} \
   CONFIG.PCW_DCI_PERIPHERAL_DIVISOR0 {15} \
   CONFIG.PCW_DCI_PERIPHERAL_DIVISOR1 {7} \
   CONFIG.PCW_DCI_PERIPHERAL_FREQMHZ {10.159} \
   CONFIG.PCW_DDRPLL_CTRL_FBDIV {32} \
   CONFIG.PCW_DDR_DDR_PLL_FREQMHZ {1066.667} \
   CONFIG.PCW_DDR_HPRLPR_QUEUE_PARTITION {HPR(0)/LPR(32)} \
   CONFIG.PCW_DDR_HPR_TO_CRITICAL_PRIORITY_LEVEL {15} \
   CONFIG.PCW_DDR_LPR_TO_CRITICAL_PRIORITY_LEVEL {2} \
   CONFIG.PCW_DDR_PERIPHERAL_CLKSRC {DDR PLL} \
   CONFIG.PCW_DDR_PERIPHERAL_DIVISOR0 {2} \
   CONFIG.PCW_DDR_PORT0_HPR_ENABLE {0} \
   CONFIG.PCW_DDR_PORT1_HPR_ENABLE {0} \
   CONFIG.PCW_DDR_PORT2_HPR_ENABLE {0} \
   CONFIG.PCW_DDR_PORT3_HPR_ENABLE {0} \
   CONFIG.PCW_DDR_RAM_BASEADDR {0x00100000} \
   CONFIG.PCW_DDR_RAM_HIGHADDR {0x1FFFFFFF} \
   CONFIG.PCW_DDR_WRITE_TO_CRITICAL_PRIORITY_LEVEL {2} \
   CONFIG.PCW_DM_WIDTH {4} \
   CONFIG.PCW_DQS_WIDTH {4} \
   CONFIG.PCW_DQ_WIDTH {32} \
   CONFIG.PCW_ENET0_BASEADDR {0xE000B000} \
   CONFIG.PCW_ENET0_GRP_MDIO_ENABLE {0} \
   CONFIG.PCW_ENET0_HIGHADDR {0xE000BFFF} \
   CONFIG.PCW_ENET0_PERIPHERAL_CLKSRC {IO PLL} \
   CONFIG.PCW_ENET0_PERIPHERAL_DIVISOR0 {1} \
   CONFIG.PCW_ENET0_PERIPHERAL_DIVISOR1 {1} \
   CONFIG.PCW_ENET0_PERIPHERAL_ENABLE {0} \
   CONFIG.PCW_ENET0_PERIPHERAL_FREQMHZ {1000 Mbps} \
   CONFIG.PCW_ENET0_RESET_ENABLE {0} \
   CONFIG.PCW_ENET1_BASEADDR {0xE000C000} \
   CONFIG.PCW_ENET1_GRP_MDIO_ENABLE {0} \
   CONFIG.PCW_ENET1_HIGHADDR {0xE000CFFF} \
   CONFIG.PCW_ENET1_PERIPHERAL_CLKSRC {IO PLL} \
   CONFIG.PCW_ENET1_PERIPHERAL_DIVISOR0 {1} \
   CONFIG.PCW_ENET1_PERIPHERAL_DIVISOR1 {1} \
   CONFIG.PCW_ENET1_PERIPHERAL_ENABLE {0} \
   CONFIG.PCW_ENET1_PERIPHERAL_FREQMHZ {1000 Mbps} \
   CONFIG.PCW_ENET1_RESET_ENABLE {0} \
   CONFIG.PCW_ENET_RESET_ENABLE {0} \
   CONFIG.PCW_ENET_RESET_POLARITY {Active Low} \
   CONFIG.PCW_EN_4K_TIMER {0} \
   CONFIG.PCW_EN_CAN0 {0} \
   CONFIG.PCW_EN_CAN1 {0} \
   CONFIG.PCW_EN_CLK0_PORT {1} \
   CONFIG.PCW_EN_CLK1_PORT {0} \
   CONFIG.PCW_EN_CLK2_PORT {0} \
   CONFIG.PCW_EN_CLK3_PORT {0} \
   CONFIG.PCW_EN_CLKTRIG0_PORT {0} \
   CONFIG.PCW_EN_CLKTRIG1_PORT {0} \
   CONFIG.PCW_EN_CLKTRIG2_PORT {0} \
   CONFIG.PCW_EN_CLKTRIG3_PORT {0} \
   CONFIG.PCW_EN_DDR {1} \
   CONFIG.PCW_EN_EMIO_CAN0 {0} \
   CONFIG.PCW_EN_EMIO_CAN1 {0} \
   CONFIG.PCW_EN_EMIO_CD_SDIO0 {0} \
   CONFIG.PCW_EN_EMIO_CD_SDIO1 {0} \
   CONFIG.PCW_EN_EMIO_ENET0 {0} \
   CONFIG.PCW_EN_EMIO_ENET1 {0} \
   CONFIG.PCW_EN_EMIO_GPIO {0} \
   CONFIG.PCW_EN_EMIO_I2C0 {0} \
   CONFIG.PCW_EN_EMIO_I2C1 {0} \
   CONFIG.PCW_EN_EMIO_MODEM_UART0 {0} \
   CONFIG.PCW_EN_EMIO_MODEM_UART1 {0} \
   CONFIG.PCW_EN_EMIO_PJTAG {0} \
   CONFIG.PCW_EN_EMIO_SDIO0 {0} \
   CONFIG.PCW_EN_EMIO_SDIO1 {0} \
   CONFIG.PCW_EN_EMIO_SPI0 {0} \
   CONFIG.PCW_EN_EMIO_SPI1 {0} \
   CONFIG.PCW_EN_EMIO_SRAM_INT {0} \
   CONFIG.PCW_EN_EMIO_TRACE {0} \
   CONFIG.PCW_EN_EMIO_TTC0 {0} \
   CONFIG.PCW_EN_EMIO_TTC1 {0} \
   CONFIG.PCW_EN_EMIO_UART0 {0} \
   CONFIG.PCW_EN_EMIO_UART1 {0} \
   CONFIG.PCW_EN_EMIO_WDT {0} \
   CONFIG.PCW_EN_EMIO_WP_SDIO0 {0} \
   CONFIG.PCW_EN_EMIO_WP_SDIO1 {0} \
   CONFIG.PCW_EN_ENET0 {0} \
   CONFIG.PCW_EN_ENET1 {0} \
   CONFIG.PCW_EN_GPIO {0} \
   CONFIG.PCW_EN_I2C0 {0} \
   CONFIG.PCW_EN_I2C1 {0} \
   CONFIG.PCW_EN_MODEM_UART0 {0} \
   CONFIG.PCW_EN_MODEM_UART1 {0} \
   CONFIG.PCW_EN_PJTAG {0} \
   CONFIG.PCW_EN_PTP_ENET0 {0} \
   CONFIG.PCW_EN_PTP_ENET1 {0} \
   CONFIG.PCW_EN_QSPI {0} \
   CONFIG.PCW_EN_RST0_PORT {1} \
   CONFIG.PCW_EN_RST1_PORT {0} \
   CONFIG.PCW_EN_RST2_PORT {0} \
   CONFIG.PCW_EN_RST3_PORT {0} \
   CONFIG.PCW_EN_SDIO0 {0} \
   CONFIG.PCW_EN_SDIO1 {0} \
   CONFIG.PCW_EN_SMC {0} \
   CONFIG.PCW_EN_SPI0 {0} \
   CONFIG.PCW_EN_SPI1 {0} \
   CONFIG.PCW_EN_TRACE {0} \
   CONFIG.PCW_EN_TTC0 {0} \
   CONFIG.PCW_EN_TTC1 {0} \
   CONFIG.PCW_EN_UART0 {0} \
   CONFIG.PCW_EN_UART1 {0} \
   CONFIG.PCW_EN_USB0 {0} \
   CONFIG.PCW_EN_USB1 {0} \
   CONFIG.PCW_EN_WDT {0} \
   CONFIG.PCW_FCLK0_PERIPHERAL_CLKSRC {IO PLL} \
   CONFIG.PCW_FCLK0_PERIPHERAL_DIVISOR0 {8} \
   CONFIG.PCW_FCLK0_PERIPHERAL_DIVISOR1 {4} \
   CONFIG.PCW_FCLK1_PERIPHERAL_CLKSRC {IO PLL} \
   CONFIG.PCW_FCLK1_PERIPHERAL_DIVISOR0 {1} \
   CONFIG.PCW_FCLK1_PERIPHERAL_DIVISOR1 {1} \
   CONFIG.PCW_FCLK2_PERIPHERAL_CLKSRC {IO PLL} \
   CONFIG.PCW_FCLK2_PERIPHERAL_DIVISOR0 {1} \
   CONFIG.PCW_FCLK2_PERIPHERAL_DIVISOR1 {1} \
   CONFIG.PCW_FCLK3_PERIPHERAL_CLKSRC {IO PLL} \
   CONFIG.PCW_FCLK3_PERIPHERAL_DIVISOR0 {1} \
   CONFIG.PCW_FCLK3_PERIPHERAL_DIVISOR1 {1} \
   CONFIG.PCW_FCLK_CLK0_BUF {TRUE} \
   CONFIG.PCW_FCLK_CLK1_BUF {FALSE} \
   CONFIG.PCW_FCLK_CLK2_BUF {FALSE} \
   CONFIG.PCW_FCLK_CLK3_BUF {FALSE} \
   CONFIG.PCW_FPGA0_PERIPHERAL_FREQMHZ {50} \
   CONFIG.PCW_FPGA1_PERIPHERAL_FREQMHZ {50} \
   CONFIG.PCW_FPGA2_PERIPHERAL_FREQMHZ {50} \
   CONFIG.PCW_FPGA3_PERIPHERAL_FREQMHZ {50} \
   CONFIG.PCW_FPGA_FCLK0_ENABLE {1} \
   CONFIG.PCW_FPGA_FCLK1_ENABLE {0} \
   CONFIG.PCW_FPGA_FCLK2_ENABLE {0} \
   CONFIG.PCW_FPGA_FCLK3_ENABLE {0} \
   CONFIG.PCW_GP0_EN_MODIFIABLE_TXN {1} \
   CONFIG.PCW_GP0_NUM_READ_THREADS {4} \
   CONFIG.PCW_GP0_NUM_WRITE_THREADS {4} \
   CONFIG.PCW_GP1_EN_MODIFIABLE_TXN {1} \
   CONFIG.PCW_GP1_NUM_READ_THREADS {4} \
   CONFIG.PCW_GP1_NUM_WRITE_THREADS {4} \
   CONFIG.PCW_GPIO_BASEADDR {0xE000A000} \
   CONFIG.PCW_GPIO_EMIO_GPIO_ENABLE {0} \
   CONFIG.PCW_GPIO_EMIO_GPIO_WIDTH {64} \
   CONFIG.PCW_GPIO_HIGHADDR {0xE000AFFF} \
   CONFIG.PCW_GPIO_MIO_GPIO_ENABLE {0} \
   CONFIG.PCW_GPIO_PERIPHERAL_ENABLE {0} \
   CONFIG.PCW_I2C0_BASEADDR {0xE0004000} \
   CONFIG.PCW_I2C0_GRP_INT_ENABLE {0} \
   CONFIG.PCW_I2C0_HIGHADDR {0xE0004FFF} \
   CONFIG.PCW_I2C0_PERIPHERAL_ENABLE {0} \
   CONFIG.PCW_I2C0_RESET_ENABLE {0} \
   CONFIG.PCW_I2C1_BASEADDR {0xE0005000} \
   CONFIG.PCW_I2C1_GRP_INT_ENABLE {0} \
   CONFIG.PCW_I2C1_HIGHADDR {0xE0005FFF} \
   CONFIG.PCW_I2C1_PERIPHERAL_ENABLE {0} \
   CONFIG.PCW_I2C1_RESET_ENABLE {0} \
   CONFIG.PCW_I2C_PERIPHERAL_FREQMHZ {25} \
   CONFIG.PCW_I2C_RESET_ENABLE {0} \
   CONFIG.PCW_I2C_RESET_POLARITY {Active Low} \
   CONFIG.PCW_IMPORT_BOARD_PRESET {None} \
   CONFIG.PCW_INCLUDE_ACP_TRANS_CHECK {0} \
   CONFIG.PCW_INCLUDE_TRACE_BUFFER {0} \
   CONFIG.PCW_IOPLL_CTRL_FBDIV {48} \
   CONFIG.PCW_IO_IO_PLL_FREQMHZ {1600.000} \
   CONFIG.PCW_IRQ_F2P_INTR {0} \
   CONFIG.PCW_IRQ_F2P_MODE {DIRECT} \
   CONFIG.PCW_MIO_PRIMITIVE {54} \
   CONFIG.PCW_MIO_TREE_PERIPHERALS {unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned} \
   CONFIG.PCW_MIO_TREE_SIGNALS {unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned#unassigned} \
   CONFIG.PCW_M_AXI_GP0_ENABLE_STATIC_REMAP {0} \
   CONFIG.PCW_M_AXI_GP0_ID_WIDTH {12} \
   CONFIG.PCW_M_AXI_GP0_SUPPORT_NARROW_BURST {0} \
   CONFIG.PCW_M_AXI_GP0_THREAD_ID_WIDTH {12} \
   CONFIG.PCW_M_AXI_GP1_ENABLE_STATIC_REMAP {0} \
   CONFIG.PCW_M_AXI_GP1_ID_WIDTH {12} \
   CONFIG.PCW_M_AXI_GP1_SUPPORT_NARROW_BURST {0} \
   CONFIG.PCW_M_AXI_GP1_THREAD_ID_WIDTH {12} \
   CONFIG.PCW_NAND_CYCLES_T_AR {1} \
   CONFIG.PCW_NAND_CYCLES_T_CLR {1} \
   CONFIG.PCW_NAND_CYCLES_T_RC {11} \
   CONFIG.PCW_NAND_CYCLES_T_REA {1} \
   CONFIG.PCW_NAND_CYCLES_T_RR {1} \
   CONFIG.PCW_NAND_CYCLES_T_WC {11} \
   CONFIG.PCW_NAND_CYCLES_T_WP {1} \
   CONFIG.PCW_NAND_GRP_D8_ENABLE {0} \
   CONFIG.PCW_NAND_PERIPHERAL_ENABLE {0} \
   CONFIG.PCW_NOR_CS0_T_CEOE {1} \
   CONFIG.PCW_NOR_CS0_T_PC {1} \
   CONFIG.PCW_NOR_CS0_T_RC {11} \
   CONFIG.PCW_NOR_CS0_T_TR {1} \
   CONFIG.PCW_NOR_CS0_T_WC {11} \
   CONFIG.PCW_NOR_CS0_T_WP {1} \
   CONFIG.PCW_NOR_CS0_WE_TIME {0} \
   CONFIG.PCW_NOR_CS1_T_CEOE {1} \
   CONFIG.PCW_NOR_CS1_T_PC {1} \
   CONFIG.PCW_NOR_CS1_T_RC {11} \
   CONFIG.PCW_NOR_CS1_T_TR {1} \
   CONFIG.PCW_NOR_CS1_T_WC {11} \
   CONFIG.PCW_NOR_CS1_T_WP {1} \
   CONFIG.PCW_NOR_CS1_WE_TIME {0} \
   CONFIG.PCW_NOR_GRP_A25_ENABLE {0} \
   CONFIG.PCW_NOR_GRP_CS0_ENABLE {0} \
   CONFIG.PCW_NOR_GRP_CS1_ENABLE {0} \
   CONFIG.PCW_NOR_GRP_SRAM_CS0_ENABLE {0} \
   CONFIG.PCW_NOR_GRP_SRAM_CS1_ENABLE {0} \
   CONFIG.PCW_NOR_GRP_SRAM_INT_ENABLE {0} \
   CONFIG.PCW_NOR_PERIPHERAL_ENABLE {0} \
   CONFIG.PCW_NOR_SRAM_CS0_T_CEOE {1} \
   CONFIG.PCW_NOR_SRAM_CS0_T_PC {1} \
   CONFIG.PCW_NOR_SRAM_CS0_T_RC {11} \
   CONFIG.PCW_NOR_SRAM_CS0_T_TR {1} \
   CONFIG.PCW_NOR_SRAM_CS0_T_WC {11} \
   CONFIG.PCW_NOR_SRAM_CS0_T_WP {1} \
   CONFIG.PCW_NOR_SRAM_CS0_WE_TIME {0} \
   CONFIG.PCW_NOR_SRAM_CS1_T_CEOE {1} \
   CONFIG.PCW_NOR_SRAM_CS1_T_PC {1} \
   CONFIG.PCW_NOR_SRAM_CS1_T_RC {11} \
   CONFIG.PCW_NOR_SRAM_CS1_T_TR {1} \
   CONFIG.PCW_NOR_SRAM_CS1_T_WC {11} \
   CONFIG.PCW_NOR_SRAM_CS1_T_WP {1} \
   CONFIG.PCW_NOR_SRAM_CS1_WE_TIME {0} \
   CONFIG.PCW_OVERRIDE_BASIC_CLOCK {0} \
   CONFIG.PCW_P2F_CAN0_INTR {0} \
   CONFIG.PCW_P2F_CAN1_INTR {0} \
   CONFIG.PCW_P2F_CTI_INTR {0} \
   CONFIG.PCW_P2F_DMAC0_INTR {0} \
   CONFIG.PCW_P2F_DMAC1_INTR {0} \
   CONFIG.PCW_P2F_DMAC2_INTR {0} \
   CONFIG.PCW_P2F_DMAC3_INTR {0} \
   CONFIG.PCW_P2F_DMAC4_INTR {0} \
   CONFIG.PCW_P2F_DMAC5_INTR {0} \
   CONFIG.PCW_P2F_DMAC6_INTR {0} \
   CONFIG.PCW_P2F_DMAC7_INTR {0} \
   CONFIG.PCW_P2F_DMAC_ABORT_INTR {0} \
   CONFIG.PCW_P2F_ENET0_INTR {0} \
   CONFIG.PCW_P2F_ENET1_INTR {0} \
   CONFIG.PCW_P2F_GPIO_INTR {0} \
   CONFIG.PCW_P2F_I2C0_INTR {0} \
   CONFIG.PCW_P2F_I2C1_INTR {0} \
   CONFIG.PCW_P2F_QSPI_INTR {0} \
   CONFIG.PCW_P2F_SDIO0_INTR {0} \
   CONFIG.PCW_P2F_SDIO1_INTR {0} \
   CONFIG.PCW_P2F_SMC_INTR {0} \
   CONFIG.PCW_P2F_SPI0_INTR {0} \
   CONFIG.PCW_P2F_SPI1_INTR {0} \
   CONFIG.PCW_P2F_UART0_INTR {0} \
   CONFIG.PCW_P2F_UART1_INTR {0} \
   CONFIG.PCW_P2F_USB0_INTR {0} \
   CONFIG.PCW_P2F_USB1_INTR {0} \
   CONFIG.PCW_PACKAGE_DDR_BOARD_DELAY0 {0.089} \
   CONFIG.PCW_PACKAGE_DDR_BOARD_DELAY1 {0.075} \
   CONFIG.PCW_PACKAGE_DDR_BOARD_DELAY2 {0.085} \
   CONFIG.PCW_PACKAGE_DDR_BOARD_DELAY3 {0.092} \
   CONFIG.PCW_PACKAGE_DDR_DQS_TO_CLK_DELAY_0 {-0.025} \
   CONFIG.PCW_PACKAGE_DDR_DQS_TO_CLK_DELAY_1 {0.014} \
   CONFIG.PCW_PACKAGE_DDR_DQS_TO_CLK_DELAY_2 {-0.009} \
   CONFIG.PCW_PACKAGE_DDR_DQS_TO_CLK_DELAY_3 {-0.033} \
   CONFIG.PCW_PACKAGE_NAME {clg400} \
   CONFIG.PCW_PCAP_PERIPHERAL_CLKSRC {IO PLL} \
   CONFIG.PCW_PCAP_PERIPHERAL_DIVISOR0 {8} \
   CONFIG.PCW_PCAP_PERIPHERAL_FREQMHZ {200} \
   CONFIG.PCW_PERIPHERAL_BOARD_PRESET {part0} \
   CONFIG.PCW_PJTAG_PERIPHERAL_ENABLE {0} \
   CONFIG.PCW_PLL_BYPASSMODE_ENABLE {0} \
   CONFIG.PCW_PRESET_BANK0_VOLTAGE {LVCMOS 3.3V} \
   CONFIG.PCW_PRESET_BANK1_VOLTAGE {LVCMOS 3.3V} \
   CONFIG.PCW_PS7_SI_REV {PRODUCTION} \
   CONFIG.PCW_QSPI_GRP_FBCLK_ENABLE {0} \
   CONFIG.PCW_QSPI_GRP_IO1_ENABLE {0} \
   CONFIG.PCW_QSPI_GRP_SINGLE_SS_ENABLE {0} \
   CONFIG.PCW_QSPI_GRP_SS1_ENABLE {0} \
   CONFIG.PCW_QSPI_INTERNAL_HIGHADDRESS {0xFCFFFFFF} \
   CONFIG.PCW_QSPI_PERIPHERAL_CLKSRC {IO PLL} \
   CONFIG.PCW_QSPI_PERIPHERAL_DIVISOR0 {1} \
   CONFIG.PCW_QSPI_PERIPHERAL_ENABLE {0} \
   CONFIG.PCW_QSPI_PERIPHERAL_FREQMHZ {200} \
   CONFIG.PCW_SD0_GRP_CD_ENABLE {0} \
   CONFIG.PCW_SD0_GRP_POW_ENABLE {0} \
   CONFIG.PCW_SD0_GRP_WP_ENABLE {0} \
   CONFIG.PCW_SD0_PERIPHERAL_ENABLE {0} \
   CONFIG.PCW_SD1_GRP_CD_ENABLE {0} \
   CONFIG.PCW_SD1_GRP_POW_ENABLE {0} \
   CONFIG.PCW_SD1_GRP_WP_ENABLE {0} \
   CONFIG.PCW_SD1_PERIPHERAL_ENABLE {0} \
   CONFIG.PCW_SDIO0_BASEADDR {0xE0100000} \
   CONFIG.PCW_SDIO0_HIGHADDR {0xE0100FFF} \
   CONFIG.PCW_SDIO1_BASEADDR {0xE0101000} \
   CONFIG.PCW_SDIO1_HIGHADDR {0xE0101FFF} \
   CONFIG.PCW_SDIO_PERIPHERAL_CLKSRC {IO PLL} \
   CONFIG.PCW_SDIO_PERIPHERAL_DIVISOR0 {1} \
   CONFIG.PCW_SDIO_PERIPHERAL_FREQMHZ {100} \
   CONFIG.PCW_SDIO_PERIPHERAL_VALID {0} \
   CONFIG.PCW_SMC_CYCLE_T0 {NA} \
   CONFIG.PCW_SMC_CYCLE_T1 {NA} \
   CONFIG.PCW_SMC_CYCLE_T2 {NA} \
   CONFIG.PCW_SMC_CYCLE_T3 {NA} \
   CONFIG.PCW_SMC_CYCLE_T4 {NA} \
   CONFIG.PCW_SMC_CYCLE_T5 {NA} \
   CONFIG.PCW_SMC_CYCLE_T6 {NA} \
   CONFIG.PCW_SMC_PERIPHERAL_CLKSRC {IO PLL} \
   CONFIG.PCW_SMC_PERIPHERAL_DIVISOR0 {1} \
   CONFIG.PCW_SMC_PERIPHERAL_FREQMHZ {100} \
   CONFIG.PCW_SMC_PERIPHERAL_VALID {0} \
   CONFIG.PCW_SPI0_BASEADDR {0xE0006000} \
   CONFIG.PCW_SPI0_GRP_SS0_ENABLE {0} \
   CONFIG.PCW_SPI0_GRP_SS1_ENABLE {0} \
   CONFIG.PCW_SPI0_GRP_SS2_ENABLE {0} \
   CONFIG.PCW_SPI0_HIGHADDR {0xE0006FFF} \
   CONFIG.PCW_SPI0_PERIPHERAL_ENABLE {0} \
   CONFIG.PCW_SPI1_BASEADDR {0xE0007000} \
   CONFIG.PCW_SPI1_GRP_SS0_ENABLE {0} \
   CONFIG.PCW_SPI1_GRP_SS1_ENABLE {0} \
   CONFIG.PCW_SPI1_GRP_SS2_ENABLE {0} \
   CONFIG.PCW_SPI1_HIGHADDR {0xE0007FFF} \
   CONFIG.PCW_SPI1_PERIPHERAL_ENABLE {0} \
   CONFIG.PCW_SPI_PERIPHERAL_CLKSRC {IO PLL} \
   CONFIG.PCW_SPI_PERIPHERAL_DIVISOR0 {1} \
   CONFIG.PCW_SPI_PERIPHERAL_FREQMHZ {166.666666} \
   CONFIG.PCW_SPI_PERIPHERAL_VALID {0} \
   CONFIG.PCW_S_AXI_ACP_ARUSER_VAL {31} \
   CONFIG.PCW_S_AXI_ACP_AWUSER_VAL {31} \
   CONFIG.PCW_S_AXI_ACP_ID_WIDTH {3} \
   CONFIG.PCW_S_AXI_GP0_ID_WIDTH {6} \
   CONFIG.PCW_S_AXI_GP1_ID_WIDTH {6} \
   CONFIG.PCW_S_AXI_HP0_DATA_WIDTH {64} \
   CONFIG.PCW_S_AXI_HP0_ID_WIDTH {6} \
   CONFIG.PCW_S_AXI_HP1_DATA_WIDTH {64} \
   CONFIG.PCW_S_AXI_HP1_ID_WIDTH {6} \
   CONFIG.PCW_S_AXI_HP2_DATA_WIDTH {64} \
   CONFIG.PCW_S_AXI_HP2_ID_WIDTH {6} \
   CONFIG.PCW_S_AXI_HP3_DATA_WIDTH {64} \
   CONFIG.PCW_S_AXI_HP3_ID_WIDTH {6} \
   CONFIG.PCW_TPIU_PERIPHERAL_CLKSRC {External} \
   CONFIG.PCW_TPIU_PERIPHERAL_DIVISOR0 {1} \
   CONFIG.PCW_TPIU_PERIPHERAL_FREQMHZ {200} \
   CONFIG.PCW_TRACE_BUFFER_CLOCK_DELAY {12} \
   CONFIG.PCW_TRACE_BUFFER_FIFO_SIZE {128} \
   CONFIG.PCW_TRACE_GRP_16BIT_ENABLE {0} \
   CONFIG.PCW_TRACE_GRP_2BIT_ENABLE {0} \
   CONFIG.PCW_TRACE_GRP_32BIT_ENABLE {0} \
   CONFIG.PCW_TRACE_GRP_4BIT_ENABLE {0} \
   CONFIG.PCW_TRACE_GRP_8BIT_ENABLE {0} \
   CONFIG.PCW_TRACE_INTERNAL_WIDTH {2} \
   CONFIG.PCW_TRACE_PERIPHERAL_ENABLE {0} \
   CONFIG.PCW_TRACE_PIPELINE_WIDTH {8} \
   CONFIG.PCW_TTC0_BASEADDR {0xE0104000} \
   CONFIG.PCW_TTC0_CLK0_PERIPHERAL_CLKSRC {CPU_1X} \
   CONFIG.PCW_TTC0_CLK0_PERIPHERAL_DIVISOR0 {1} \
   CONFIG.PCW_TTC0_CLK0_PERIPHERAL_FREQMHZ {133.333333} \
   CONFIG.PCW_TTC0_CLK1_PERIPHERAL_CLKSRC {CPU_1X} \
   CONFIG.PCW_TTC0_CLK1_PERIPHERAL_DIVISOR0 {1} \
   CONFIG.PCW_TTC0_CLK1_PERIPHERAL_FREQMHZ {133.333333} \
   CONFIG.PCW_TTC0_CLK2_PERIPHERAL_CLKSRC {CPU_1X} \
   CONFIG.PCW_TTC0_CLK2_PERIPHERAL_DIVISOR0 {1} \
   CONFIG.PCW_TTC0_CLK2_PERIPHERAL_FREQMHZ {133.333333} \
   CONFIG.PCW_TTC0_HIGHADDR {0xE0104fff} \
   CONFIG.PCW_TTC0_PERIPHERAL_ENABLE {0} \
   CONFIG.PCW_TTC1_BASEADDR {0xE0105000} \
   CONFIG.PCW_TTC1_CLK0_PERIPHERAL_CLKSRC {CPU_1X} \
   CONFIG.PCW_TTC1_CLK0_PERIPHERAL_DIVISOR0 {1} \
   CONFIG.PCW_TTC1_CLK0_PERIPHERAL_FREQMHZ {133.333333} \
   CONFIG.PCW_TTC1_CLK1_PERIPHERAL_CLKSRC {CPU_1X} \
   CONFIG.PCW_TTC1_CLK1_PERIPHERAL_DIVISOR0 {1} \
   CONFIG.PCW_TTC1_CLK1_PERIPHERAL_FREQMHZ {133.333333} \
   CONFIG.PCW_TTC1_CLK2_PERIPHERAL_CLKSRC {CPU_1X} \
   CONFIG.PCW_TTC1_CLK2_PERIPHERAL_DIVISOR0 {1} \
   CONFIG.PCW_TTC1_CLK2_PERIPHERAL_FREQMHZ {133.333333} \
   CONFIG.PCW_TTC1_HIGHADDR {0xE0105fff} \
   CONFIG.PCW_TTC1_PERIPHERAL_ENABLE {0} \
   CONFIG.PCW_TTC_PERIPHERAL_FREQMHZ {50} \
   CONFIG.PCW_UART0_BASEADDR {0xE0000000} \
   CONFIG.PCW_UART0_BAUD_RATE {115200} \
   CONFIG.PCW_UART0_GRP_FULL_ENABLE {0} \
   CONFIG.PCW_UART0_HIGHADDR {0xE0000FFF} \
   CONFIG.PCW_UART0_PERIPHERAL_ENABLE {0} \
   CONFIG.PCW_UART1_BASEADDR {0xE0001000} \
   CONFIG.PCW_UART1_BAUD_RATE {115200} \
   CONFIG.PCW_UART1_GRP_FULL_ENABLE {0} \
   CONFIG.PCW_UART1_HIGHADDR {0xE0001FFF} \
   CONFIG.PCW_UART1_PERIPHERAL_ENABLE {0} \
   CONFIG.PCW_UART_PERIPHERAL_CLKSRC {IO PLL} \
   CONFIG.PCW_UART_PERIPHERAL_DIVISOR0 {1} \
   CONFIG.PCW_UART_PERIPHERAL_FREQMHZ {100} \
   CONFIG.PCW_UART_PERIPHERAL_VALID {0} \
   CONFIG.PCW_UIPARAM_ACT_DDR_FREQ_MHZ {533.333374} \
   CONFIG.PCW_UIPARAM_DDR_ADV_ENABLE {0} \
   CONFIG.PCW_UIPARAM_DDR_AL {0} \
   CONFIG.PCW_UIPARAM_DDR_BANK_ADDR_COUNT {3} \
   CONFIG.PCW_UIPARAM_DDR_BL {8} \
   CONFIG.PCW_UIPARAM_DDR_BOARD_DELAY0 {0.25} \
   CONFIG.PCW_UIPARAM_DDR_BOARD_DELAY1 {0.25} \
   CONFIG.PCW_UIPARAM_DDR_BOARD_DELAY2 {0.25} \
   CONFIG.PCW_UIPARAM_DDR_BOARD_DELAY3 {0.25} \
   CONFIG.PCW_UIPARAM_DDR_BUS_WIDTH {32 Bit} \
   CONFIG.PCW_UIPARAM_DDR_CL {7} \
   CONFIG.PCW_UIPARAM_DDR_CLOCK_0_LENGTH_MM {0} \
   CONFIG.PCW_UIPARAM_DDR_CLOCK_0_PACKAGE_LENGTH {80.4535} \
   CONFIG.PCW_UIPARAM_DDR_CLOCK_0_PROPOGATION_DELAY {160} \
   CONFIG.PCW_UIPARAM_DDR_CLOCK_1_LENGTH_MM {0} \
   CONFIG.PCW_UIPARAM_DDR_CLOCK_1_PACKAGE_LENGTH {80.4535} \
   CONFIG.PCW_UIPARAM_DDR_CLOCK_1_PROPOGATION_DELAY {160} \
   CONFIG.PCW_UIPARAM_DDR_CLOCK_2_LENGTH_MM {0} \
   CONFIG.PCW_UIPARAM_DDR_CLOCK_2_PACKAGE_LENGTH {80.4535} \
   CONFIG.PCW_UIPARAM_DDR_CLOCK_2_PROPOGATION_DELAY {160} \
   CONFIG.PCW_UIPARAM_DDR_CLOCK_3_LENGTH_MM {0} \
   CONFIG.PCW_UIPARAM_DDR_CLOCK_3_PACKAGE_LENGTH {80.4535} \
   CONFIG.PCW_UIPARAM_DDR_CLOCK_3_PROPOGATION_DELAY {160} \
   CONFIG.PCW_UIPARAM_DDR_CLOCK_STOP_EN {0} \
   CONFIG.PCW_UIPARAM_DDR_COL_ADDR_COUNT {10} \
   CONFIG.PCW_UIPARAM_DDR_CWL {6} \
   CONFIG.PCW_UIPARAM_DDR_DEVICE_CAPACITY {1024 MBits} \
   CONFIG.PCW_UIPARAM_DDR_DQS_0_LENGTH_MM {0} \
   CONFIG.PCW_UIPARAM_DDR_DQS_0_PACKAGE_LENGTH {105.056} \
   CONFIG.PCW_UIPARAM_DDR_DQS_0_PROPOGATION_DELAY {160} \
   CONFIG.PCW_UIPARAM_DDR_DQS_1_LENGTH_MM {0} \
   CONFIG.PCW_UIPARAM_DDR_DQS_1_PACKAGE_LENGTH {66.904} \
   CONFIG.PCW_UIPARAM_DDR_DQS_1_PROPOGATION_DELAY {160} \
   CONFIG.PCW_UIPARAM_DDR_DQS_2_LENGTH_MM {0} \
   CONFIG.PCW_UIPARAM_DDR_DQS_2_PACKAGE_LENGTH {89.1715} \
   CONFIG.PCW_UIPARAM_DDR_DQS_2_PROPOGATION_DELAY {160} \
   CONFIG.PCW_UIPARAM_DDR_DQS_3_LENGTH_MM {0} \
   CONFIG.PCW_UIPARAM_DDR_DQS_3_PACKAGE_LENGTH {113.63} \
   CONFIG.PCW_UIPARAM_DDR_DQS_3_PROPOGATION_DELAY {160} \
   CONFIG.PCW_UIPARAM_DDR_DQS_TO_CLK_DELAY_0 {0.0} \
   CONFIG.PCW_UIPARAM_DDR_DQS_TO_CLK_DELAY_1 {0.0} \
   CONFIG.PCW_UIPARAM_DDR_DQS_TO_CLK_DELAY_2 {0.0} \
   CONFIG.PCW_UIPARAM_DDR_DQS_TO_CLK_DELAY_3 {0.0} \
   CONFIG.PCW_UIPARAM_DDR_DQ_0_LENGTH_MM {0} \
   CONFIG.PCW_UIPARAM_DDR_DQ_0_PACKAGE_LENGTH {98.503} \
   CONFIG.PCW_UIPARAM_DDR_DQ_0_PROPOGATION_DELAY {160} \
   CONFIG.PCW_UIPARAM_DDR_DQ_1_LENGTH_MM {0} \
   CONFIG.PCW_UIPARAM_DDR_DQ_1_PACKAGE_LENGTH {68.5855} \
   CONFIG.PCW_UIPARAM_DDR_DQ_1_PROPOGATION_DELAY {160} \
   CONFIG.PCW_UIPARAM_DDR_DQ_2_LENGTH_MM {0} \
   CONFIG.PCW_UIPARAM_DDR_DQ_2_PACKAGE_LENGTH {90.295} \
   CONFIG.PCW_UIPARAM_DDR_DQ_2_PROPOGATION_DELAY {160} \
   CONFIG.PCW_UIPARAM_DDR_DQ_3_LENGTH_MM {0} \
   CONFIG.PCW_UIPARAM_DDR_DQ_3_PACKAGE_LENGTH {103.977} \
   CONFIG.PCW_UIPARAM_DDR_DQ_3_PROPOGATION_DELAY {160} \
   CONFIG.PCW_UIPARAM_DDR_DRAM_WIDTH {8 Bits} \
   CONFIG.PCW_UIPARAM_DDR_ECC {Disabled} \
   CONFIG.PCW_UIPARAM_DDR_ENABLE {1} \
   CONFIG.PCW_UIPARAM_DDR_FREQ_MHZ {533.333333} \
   CONFIG.PCW_UIPARAM_DDR_HIGH_TEMP {Normal (0-85)} \
   CONFIG.PCW_UIPARAM_DDR_MEMORY_TYPE {DDR 3} \
   CONFIG.PCW_UIPARAM_DDR_PARTNO {MT41J128M8 JP-125} \
   CONFIG.PCW_UIPARAM_DDR_ROW_ADDR_COUNT {14} \
   CONFIG.PCW_UIPARAM_DDR_SPEED_BIN {DDR3_1066F} \
   CONFIG.PCW_UIPARAM_DDR_TRAIN_DATA_EYE {1} \
   CONFIG.PCW_UIPARAM_DDR_TRAIN_READ_GATE {1} \
   CONFIG.PCW_UIPARAM_DDR_TRAIN_WRITE_LEVEL {1} \
   CONFIG.PCW_UIPARAM_DDR_T_FAW {30.0} \
   CONFIG.PCW_UIPARAM_DDR_T_RAS_MIN {35.0} \
   CONFIG.PCW_UIPARAM_DDR_T_RC {48.75} \
   CONFIG.PCW_UIPARAM_DDR_T_RCD {7} \
   CONFIG.PCW_UIPARAM_DDR_T_RP {7} \
   CONFIG.PCW_UIPARAM_DDR_USE_INTERNAL_VREF {0} \
   CONFIG.PCW_UIPARAM_GENERATE_SUMMARY {NA} \
   CONFIG.PCW_USB0_BASEADDR {0xE0102000} \
   CONFIG.PCW_USB0_HIGHADDR {0xE0102fff} \
   CONFIG.PCW_USB0_PERIPHERAL_ENABLE {0} \
   CONFIG.PCW_USB0_PERIPHERAL_FREQMHZ {60} \
   CONFIG.PCW_USB0_RESET_ENABLE {0} \
   CONFIG.PCW_USB1_BASEADDR {0xE0103000} \
   CONFIG.PCW_USB1_HIGHADDR {0xE0103fff} \
   CONFIG.PCW_USB1_PERIPHERAL_ENABLE {0} \
   CONFIG.PCW_USB1_PERIPHERAL_FREQMHZ {60} \
   CONFIG.PCW_USB1_RESET_ENABLE {0} \
   CONFIG.PCW_USB_RESET_ENABLE {0} \
   CONFIG.PCW_USB_RESET_POLARITY {Active Low} \
   CONFIG.PCW_USE_AXI_FABRIC_IDLE {0} \
   CONFIG.PCW_USE_AXI_NONSECURE {0} \
   CONFIG.PCW_USE_CORESIGHT {0} \
   CONFIG.PCW_USE_CROSS_TRIGGER {0} \
   CONFIG.PCW_USE_CR_FABRIC {1} \
   CONFIG.PCW_USE_DDR_BYPASS {0} \
   CONFIG.PCW_USE_DEBUG {0} \
   CONFIG.PCW_USE_DEFAULT_ACP_USER_VAL {0} \
   CONFIG.PCW_USE_DMA0 {0} \
   CONFIG.PCW_USE_DMA1 {0} \
   CONFIG.PCW_USE_DMA2 {0} \
   CONFIG.PCW_USE_DMA3 {0} \
   CONFIG.PCW_USE_EXPANDED_IOP {0} \
   CONFIG.PCW_USE_EXPANDED_PS_SLCR_REGISTERS {0} \
   CONFIG.PCW_USE_FABRIC_INTERRUPT {0} \
   CONFIG.PCW_USE_HIGH_OCM {0} \
   CONFIG.PCW_USE_M_AXI_GP0 {0} \
   CONFIG.PCW_USE_M_AXI_GP1 {0} \
   CONFIG.PCW_USE_PROC_EVENT_BUS {0} \
   CONFIG.PCW_USE_PS_SLCR_REGISTERS {0} \
   CONFIG.PCW_USE_S_AXI_ACP {0} \
   CONFIG.PCW_USE_S_AXI_GP0 {0} \
   CONFIG.PCW_USE_S_AXI_GP1 {0} \
   CONFIG.PCW_USE_S_AXI_HP0 {0} \
   CONFIG.PCW_USE_S_AXI_HP1 {0} \
   CONFIG.PCW_USE_S_AXI_HP2 {0} \
   CONFIG.PCW_USE_S_AXI_HP3 {0} \
   CONFIG.PCW_USE_TRACE {0} \
   CONFIG.PCW_USE_TRACE_DATA_EDGE_DETECTOR {0} \
   CONFIG.PCW_VALUE_SILVERSION {3} \
   CONFIG.PCW_WDT_PERIPHERAL_CLKSRC {CPU_1X} \
   CONFIG.PCW_WDT_PERIPHERAL_DIVISOR0 {1} \
   CONFIG.PCW_WDT_PERIPHERAL_ENABLE {0} \
   CONFIG.PCW_WDT_PERIPHERAL_FREQMHZ {133.333333} \
 ] $processing_system7_0

  # Create instance: rst_ps7_0_50M, and set properties
  set rst_ps7_0_50M [ create_bd_cell -type ip -vlnv xilinx.com:ip:proc_sys_reset:5.0 rst_ps7_0_50M ]

  # Create interface connections
  connect_bd_intf_net -intf_net processing_system7_0_DDR [get_bd_intf_ports DDR] [get_bd_intf_pins processing_system7_0/DDR]
  connect_bd_intf_net -intf_net processing_system7_0_FIXED_IO [get_bd_intf_ports FIXED_IO] [get_bd_intf_pins processing_system7_0/FIXED_IO]

  # Create port connections
  connect_bd_net -net processing_system7_0_FCLK_CLK0 [get_bd_pins mMIPS_sim_0/clk] [get_bd_pins processing_system7_0/FCLK_CLK0] [get_bd_pins rst_ps7_0_50M/slowest_sync_clk]
  connect_bd_net -net processing_system7_0_FCLK_RESET0_N [get_bd_pins processing_system7_0/FCLK_RESET0_N] [get_bd_pins rst_ps7_0_50M/ext_reset_in]
  connect_bd_net -net rst_ps7_0_50M_interconnect_aresetn [get_bd_pins mMIPS_sim_0/en] [get_bd_pins rst_ps7_0_50M/interconnect_aresetn]
  connect_bd_net -net rst_ps7_0_50M_mb_reset [get_bd_pins mMIPS_sim_0/rst] [get_bd_pins rst_ps7_0_50M/mb_reset]

  # Create address segments


  # Restore current instance
  current_bd_instance $oldCurInst

  save_bd_design
  close_bd_design $design_name 
}
# End of cr_bd_design_1()
cr_bd_design_1 ""
set_property IS_MANAGED "0" [get_files design_1.bd ] 
set_property REGISTERED_WITH_MANAGER "1" [get_files design_1.bd ] 
set_property SYNTH_CHECKPOINT_MODE "Hierarchical" [get_files design_1.bd ] 

# Set block design to be only used in synthesis and implementation
set_property "used_in_simulation" "0" [get_files */design_1_wrapper.v]
set_property "used_in_simulation" "0" [get_files */design_1.bd]

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
    create_run -name synth_1 -part xc7z020clg400-1 -flow {Vivado Synthesis 2018} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2018" [get_runs synth_1]
}
set obj [get_runs synth_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Synthesis Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'synth_1_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0] "" ] } {
  create_report_config -report_name synth_1_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs synth_1
}
set obj [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs synth_1]
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
    create_run -name impl_1 -part xc7z020clg400-1 -flow {Vivado Implementation 2018} -strategy "Vivado Implementation Defaults" -report_strategy {No Reports} -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Implementation 2018" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Implementation Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'impl_1_init_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_init_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps init_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_opt_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_drc_0 -report_type report_drc:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_io_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0] "" ] } {
  create_report_config -report_name impl_1_place_report_io_0 -report_type report_io:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0] "" ] } {
  create_report_config -report_name impl_1_place_report_utilization_0 -report_type report_utilization:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_control_sets_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0] "" ] } {
  create_report_config -report_name impl_1_place_report_control_sets_0 -report_type report_control_sets:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_1' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_1 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_place_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_post_place_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_place_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_place_power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_route_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_route_report_drc_0 -report_type report_drc:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_methodology_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0] "" ] } {
  create_report_config -report_name impl_1_route_report_methodology_0 -report_type report_methodology:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_power_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0] "" ] } {
  create_report_config -report_name impl_1_route_report_power_0 -report_type report_power:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_route_status_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0] "" ] } {
  create_report_config -report_name impl_1_route_report_route_status_0 -report_type report_route_status:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_route_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_route_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_clock_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0] "" ] } {
  create_report_config -report_name impl_1_route_report_clock_utilization_0 -report_type report_clock_utilization:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_route_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0]
if { $obj != "" } {

}
# Create 'impl_1_post_route_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0]
if { $obj != "" } {

}
# Create 'impl_1_post_route_phys_opt_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0]
if { $obj != "" } {

}
set obj [get_runs impl_1]
set_property -name "strategy" -value "Vivado Implementation Defaults" -objects $obj
set_property -name "steps.write_bitstream.args.readback_file" -value "0" -objects $obj
set_property -name "steps.write_bitstream.args.verbose" -value "0" -objects $obj

# set the current impl run
current_run -implementation [get_runs impl_1]

puts "INFO: Project created:${_xil_proj_name_}"

start_gui